USE CleantopiaCRM;
GO

SET NOCOUNT ON;

IF OBJECT_ID('tempdb..#CountrySrc') IS NOT NULL DROP TABLE #CountrySrc;
CREATE TABLE #CountrySrc (Code NVARCHAR(10) NOT NULL, Name NVARCHAR(250) NOT NULL);

INSERT INTO #CountrySrc(Code, Name) VALUES
('AF', N'Afghanistan'),
('AL', N'Albania'),
('DZ', N'Algeria'),
('AS', N'American Samoa'),
('AD', N'Andorra'),
('AO', N'Angola'),
('AI', N'Anguilla'),
('AQ', N'Antarctica'),
('AG', N'Antigua and Barbuda'),
('AR', N'Argentina'),
('AM', N'Armenia'),
('AW', N'Aruba'),
('AU', N'Australia'),
('AT', N'Austria'),
('AZ', N'Azerbaijan'),
('BS', N'Bahamas'),
('BH', N'Bahrain'),
('BD', N'Bangladesh'),
('BB', N'Barbados'),
('BY', N'Belarus'),
('BE', N'Belgium'),
('BZ', N'Belize'),
('BJ', N'Benin'),
('BM', N'Bermuda'),
('BT', N'Bhutan'),
('BO', N'Bolivia'),
('BA', N'Bosnia and Herzegovina'),
('BW', N'Botswana'),
('BV', N'Bouvet Island'),
('BR', N'Brazil'),
('IO', N'British Indian Ocean Territory'),
('VG', N'British Virgin Islands'),
('BN', N'Brunei'),
('BG', N'Bulgaria'),
('BF', N'Burkina Faso'),
('BI', N'Burundi'),
('KH', N'Cambodia'),
('CM', N'Cameroon'),
('CA', N'Canada'),
('CV', N'Cape Verde'),
('BQ', N'Caribbean Netherlands'),
('KY', N'Cayman Islands'),
('CF', N'Central African Republic'),
('TD', N'Chad'),
('CL', N'Chile'),
('CN', N'China'),
('CX', N'Christmas Island'),
('CC', N'Cocos (Keeling) Islands'),
('CO', N'Colombia'),
('KM', N'Comoros'),
('CK', N'Cook Islands'),
('CR', N'Costa Rica'),
('HR', N'Croatia'),
('CU', N'Cuba'),
('CW', N'Curaçao'),
('CY', N'Cyprus'),
('CZ', N'Czechia'),
('CD', N'DR Congo'),
('DK', N'Denmark'),
('DJ', N'Djibouti'),
('DM', N'Dominica'),
('DO', N'Dominican Republic'),
('EC', N'Ecuador'),
('EG', N'Egypt'),
('SV', N'El Salvador'),
('GQ', N'Equatorial Guinea'),
('ER', N'Eritrea'),
('EE', N'Estonia'),
('SZ', N'Eswatini'),
('ET', N'Ethiopia'),
('FK', N'Falkland Islands'),
('FO', N'Faroe Islands'),
('FJ', N'Fiji'),
('FI', N'Finland'),
('FR', N'France'),
('GF', N'French Guiana'),
('PF', N'French Polynesia'),
('TF', N'French Southern and Antarctic Lands'),
('GA', N'Gabon'),
('GM', N'Gambia'),
('GE', N'Georgia'),
('DE', N'Germany'),
('GH', N'Ghana'),
('GI', N'Gibraltar'),
('GR', N'Greece'),
('GL', N'Greenland'),
('GD', N'Grenada'),
('GP', N'Guadeloupe'),
('GU', N'Guam'),
('GT', N'Guatemala'),
('GG', N'Guernsey'),
('GN', N'Guinea'),
('GW', N'Guinea-Bissau'),
('GY', N'Guyana'),
('HT', N'Haiti'),
('HM', N'Heard Island and McDonald Islands'),
('HN', N'Honduras'),
('HK', N'Hong Kong'),
('HU', N'Hungary'),
('IS', N'Iceland'),
('IN', N'India'),
('ID', N'Indonesia'),
('IR', N'Iran'),
('IQ', N'Iraq'),
('IE', N'Ireland'),
('IM', N'Isle of Man'),
('IL', N'Israel'),
('IT', N'Italy'),
('CI', N'Ivory Coast'),
('JM', N'Jamaica'),
('JP', N'Japan'),
('JE', N'Jersey'),
('JO', N'Jordan'),
('KZ', N'Kazakhstan'),
('KE', N'Kenya'),
('KI', N'Kiribati'),
('XK', N'Kosovo'),
('KW', N'Kuwait'),
('KG', N'Kyrgyzstan'),
('LA', N'Laos'),
('LV', N'Latvia'),
('LB', N'Lebanon'),
('LS', N'Lesotho'),
('LR', N'Liberia'),
('LY', N'Libya'),
('LI', N'Liechtenstein'),
('LT', N'Lithuania'),
('LU', N'Luxembourg'),
('MO', N'Macau'),
('MG', N'Madagascar'),
('MW', N'Malawi'),
('MY', N'Malaysia'),
('MV', N'Maldives'),
('ML', N'Mali'),
('MT', N'Malta'),
('MH', N'Marshall Islands'),
('MQ', N'Martinique'),
('MR', N'Mauritania'),
('MU', N'Mauritius'),
('YT', N'Mayotte'),
('MX', N'Mexico'),
('FM', N'Micronesia'),
('MD', N'Moldova'),
('MC', N'Monaco'),
('MN', N'Mongolia'),
('ME', N'Montenegro'),
('MS', N'Montserrat'),
('MA', N'Morocco'),
('MZ', N'Mozambique'),
('MM', N'Myanmar'),
('NA', N'Namibia'),
('NR', N'Nauru'),
('NP', N'Nepal'),
('NL', N'Netherlands'),
('NC', N'New Caledonia'),
('NZ', N'New Zealand'),
('NI', N'Nicaragua'),
('NE', N'Niger'),
('NG', N'Nigeria'),
('NU', N'Niue'),
('NF', N'Norfolk Island'),
('KP', N'North Korea'),
('MK', N'North Macedonia'),
('MP', N'Northern Mariana Islands'),
('NO', N'Norway'),
('OM', N'Oman'),
('PK', N'Pakistan'),
('PW', N'Palau'),
('PS', N'Palestine'),
('PA', N'Panama'),
('PG', N'Papua New Guinea'),
('PY', N'Paraguay'),
('PE', N'Peru'),
('PH', N'Philippines'),
('PN', N'Pitcairn Islands'),
('PL', N'Poland'),
('PT', N'Portugal'),
('PR', N'Puerto Rico'),
('QA', N'Qatar'),
('CG', N'Republic of the Congo'),
('RO', N'Romania'),
('RU', N'Russia'),
('RW', N'Rwanda'),
('RE', N'Réunion'),
('BL', N'Saint Barthélemy'),
('SH', N'Saint Helena, Ascension and Tristan da Cunha'),
('KN', N'Saint Kitts and Nevis'),
('LC', N'Saint Lucia'),
('MF', N'Saint Martin'),
('PM', N'Saint Pierre and Miquelon'),
('VC', N'Saint Vincent and the Grenadines'),
('WS', N'Samoa'),
('SM', N'San Marino'),
('SA', N'Saudi Arabia'),
('SN', N'Senegal'),
('RS', N'Serbia'),
('SC', N'Seychelles'),
('SL', N'Sierra Leone'),
('SG', N'Singapore'),
('SX', N'Sint Maarten'),
('SK', N'Slovakia'),
('SI', N'Slovenia'),
('SB', N'Solomon Islands'),
('SO', N'Somalia'),
('ZA', N'South Africa'),
('GS', N'South Georgia'),
('KR', N'South Korea'),
('SS', N'South Sudan'),
('ES', N'Spain'),
('LK', N'Sri Lanka'),
('SD', N'Sudan'),
('SR', N'Suriname'),
('SJ', N'Svalbard and Jan Mayen'),
('SE', N'Sweden'),
('CH', N'Switzerland'),
('SY', N'Syria'),
('ST', N'São Tomé and Príncipe'),
('TW', N'Taiwan'),
('TJ', N'Tajikistan'),
('TZ', N'Tanzania'),
('TH', N'Thailand'),
('TL', N'Timor-Leste'),
('TG', N'Togo'),
('TK', N'Tokelau'),
('TO', N'Tonga'),
('TT', N'Trinidad and Tobago'),
('TN', N'Tunisia'),
('TR', N'Turkey'),
('TM', N'Turkmenistan'),
('TC', N'Turks and Caicos Islands'),
('TV', N'Tuvalu'),
('UG', N'Uganda'),
('UA', N'Ukraine'),
('AE', N'United Arab Emirates'),
('GB', N'United Kingdom'),
('US', N'United States'),
('UM', N'United States Minor Outlying Islands'),
('VI', N'United States Virgin Islands'),
('UY', N'Uruguay'),
('UZ', N'Uzbekistan'),
('VU', N'Vanuatu'),
('VA', N'Vatican City'),
('VE', N'Venezuela'),
('VN', N'Vietnam'),
('WF', N'Wallis and Futuna'),
('EH', N'Western Sahara'),
('YE', N'Yemen'),
('ZM', N'Zambia'),
('ZW', N'Zimbabwe'),
('AX', N'Åland Islands');

;WITH d AS (
    SELECT Code, Name, ROW_NUMBER() OVER (PARTITION BY Code ORDER BY Name) AS rn
    FROM #CountrySrc
)
DELETE FROM d WHERE rn > 1;

UPDATE c
SET c.Name = s.Name
FROM dbo.Countries c
JOIN #CountrySrc s ON s.Code = c.Code
WHERE ISNULL(c.Name,'') <> ISNULL(s.Name,'');

INSERT INTO dbo.Countries(Code, Name)
SELECT s.Code, s.Name
FROM #CountrySrc s
LEFT JOIN dbo.Countries c ON c.Code = s.Code
WHERE c.Id IS NULL;

-- Optional cleanup (disabled by default):
-- DELETE c FROM dbo.Countries c LEFT JOIN #CountrySrc s ON s.Code = c.Code WHERE s.Code IS NULL;

DROP TABLE #CountrySrc;
GO